- arguments:
  - -XApplicativeDo
  - -XBangPatterns
  - -XConstraintKinds
  - -XDataKinds
  - -XDefaultSignatures
  - -XDeriveAnyClass
  - -XDeriveFoldable
  - -XDeriveFunctor
  - -XDeriveGeneric
  - -XDeriveLift
  - -XDeriveTraversable
  - -XDerivingStrategies
  - -XDerivingVia
  - -XEmptyCase
  - -XExistentialQuantification
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XFunctionalDependencies
  - -XGADTs
  - -XGeneralizedNewtypeDeriving
  - -XInstanceSigs
  - -XKindSignatures
  - -XLambdaCase
  - -XMultiParamTypeClasses
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XOverloadedStrings
  - -XPatternSynonyms
  - -XPolyKinds
  - -XRankNTypes
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XTemplateHaskell
  - -XTupleSections
  - -XTypeApplications
  - -XTypeFamilies
  - -XTypeFamilyDependencies
  - -XTypeOperators