name: Haskell CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  stack-build:
    name: Stack - ghc-${{ matrix.ghc }} os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - 8.10.1
          - 8.8.3
          - 8.6.5
        exclude:
          - os: macos-latest
            ghc: 8.8.3
          - os: macos-latest
            ghc: 8.6.5

    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml

    steps:
      - uses: actions/checkout@v2
        name: Checkout Source Code

      - uses: actions/setup-haskell@v1.1
        name: Setup Haskell Build Environment
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true

      - uses: actions/cache@v2
        name: Cache dependencies
        with:
          path: |
            ~/.stack
            !~/.stack/setup-exe-src
            !~/.stack/setup-exe-cache
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles(env.STACK_YAML) }}

      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --system-ghc --ta '--quickcheck-tests 100000'

      - name: Haddock
        run: stack haddock --system-ghc

      - name : Prepare sdist
        run: stack sdist --system-ghc

  cabal-build:
    name: Cabal - ghc-${{ matrix.ghc }} os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc:
          - 8.10.1
          - 8.8.3
          - 8.6.5
        exclude:
          - os: macos-latest
            ghc: 8.8.3
          - os: macos-latest
            ghc: 8.6.5

    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
      - uses: actions/checkout@v2
        name: Checkout Source Code

      - uses: actions/setup-haskell@v1.1
        name: Setup Haskell Build Environment
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: false

      - name: Update package index
        run: cabal update $CONFIG

      - name: Generate freeze file
        run: cabal freeze $CONFIG

      - uses: actions/cache@v2
        name: Cache dependencies
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-cabal-

      - name: Build
        run: cabal build all --enable-documentation $CONFIG

      - name: Test
        run: cabal test all --test-show-details=always --test-options='--quickcheck-tests 100000' $CONFIG

      - name: Haddock
        run: cabal haddock all --enable-documentation $CONFIG

      - name: Prepare sdist
        run: cabal sdist all
